name: "steam_review_analytics"
version: "0.2.0"
config-version: 2

profile: "steam_duckdb"

model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  steam_review_analytics:
    +materialized: view
    bronze:
      +schema: bronze
      +materialized: incremental
      +on_schema_change: append_new_columns
    silver:
      +schema: silver
      +materialized: incremental
    gold:
      +schema: gold
      +materialized: table