version: 2

models:
  - name: game_review_health_metrics
    description: |
      Gold layer mart capturing review health signals for each Steam game,
      including hold-up-over-time and popularity heuristics.
    columns:
      - name: app_id
        description: Steam application identifier.
        tests:
          - not_null
          - unique
      - name: record_changed_at
        description: Latest change timestamp drawn from upstream Silver data.
      - name: snapshot_date
        description: Daily grain derived from `record_changed_at` for incremental rollups.
      - name: hold_up_score
        description: |
          Change in positive review ratio between the first {{ var('early_window_days', 180) }} days
          and the most recent {{ var('recent_window_days', 180) }} days.
      - name: review_decay_ratio
        description: |
          Ratio of review volume in the most recent {{ var('decay_window_days', 90) }} days versus the
          prior {{ var('decay_window_days', 90) }}-day period.
      - name: cult_popularity_score
        description: |
          Helpful-vote weighted popularity adjusted for catalog-wide reach to
          highlight "cult classic" titles.
      - name: general_popularity_score
        description: |
          Broad popularity proxy based on total positive review volume.
